# Generated by Django 4.2.21 on 2025-05-28 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='colegios',
            fields=[
                ('nombre_colegio', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='imagenNoticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('imagen_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estudiante', models.BooleanField(default=False)),
                ('profesor', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('destacada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='inclusivo',
            fields=[
                ('id_inclusivo', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=25)),
                ('sexo', models.CharField(max_length=50)),
                ('trato', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='moodleUser',
            fields=[
                ('id_moodle', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=22)),
                ('password', models.CharField(max_length=500)),
                ('act_datos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('imagen_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estudiante', models.BooleanField(default=False)),
                ('profesor', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prospecto',
            fields=[
                ('id_prospecto', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=22)),
                ('tipo_identificacion', models.CharField(max_length=2)),
                ('estado_migratorio', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_telefonico', models.CharField(max_length=22)),
                ('numero_telefonico2', models.CharField(max_length=22, null=True)),
                ('correo_institucional', models.CharField(max_length=60)),
                ('correo_personal', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('canton', models.CharField(max_length=20)),
                ('distrito', models.CharField(max_length=20)),
                ('direccion_exacta', models.CharField(max_length=500)),
                ('sexo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='universidades',
            fields=[
                ('nombre_universidad', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='urls_dspace',
            fields=[
                ('id_urls', models.AutoField(primary_key=True, serialize=False)),
                ('id_estudiante', models.CharField(max_length=25)),
                ('tituloeducacion', models.CharField(max_length=500)),
                ('titulouniversitario', models.CharField(max_length=500)),
                ('identificacion', models.CharField(max_length=500)),
                ('fotoperfil', models.CharField(max_length=500)),
                ('record_academico', models.CharField(max_length=500)),
                ('plan_estudio', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user_status',
            fields=[
                ('id_user_status', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=22)),
                ('activo', models.BooleanField(default=True)),
                ('moroso', models.BooleanField(default=False)),
                ('terminos_condiciones', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_studies',
            fields=[
                ('id_user_studies', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=22)),
                ('estudio', models.CharField(max_length=300)),
                ('formulario', models.BooleanField(default=False)),
                ('prematricula_envio', models.BooleanField(default=False)),
                ('prematricula', models.BooleanField(default=False)),
                ('matricula', models.BooleanField(default=False)),
                ('cursando', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLogsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechatiempo', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIDUserCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechatiempo', models.DateTimeField(auto_now_add=True)),
                ('tipo_ident_nueva', models.CharField(max_length=25)),
                ('nueva_identificacion', models.CharField(max_length=25)),
                ('antigua_identifiacion', models.CharField(max_length=25)),
                ('tipo_ident_antigua', models.CharField(max_length=25)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='primerIngreso',
            fields=[
                ('id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=55)),
                ('convalidacion', models.BooleanField(default=False)),
                ('comentario', models.TextField(max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fotoperfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.BinaryField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('docTitulo', models.CharField(max_length=25)),
                ('docTituloUniversitario', models.CharField(max_length=25)),
                ('docIdentificacion', models.CharField(max_length=25)),
                ('docFotoPasaporte', models.CharField(max_length=25)),
                ('docMateriasAprobadas', models.CharField(max_length=25)),
                ('docPlanEstudios', models.CharField(max_length=25)),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=200)),
                ('archivo', models.BinaryField()),
                ('extension', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('aprobado', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
